# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference

name: sampler-smart-check-sizing
title: Sampler smart check sizing
version: 1.0.0
grade: stable
summary: Data acquisition application for smart check sizing
description: |
  This app work in pair with the application Smart Check Sizing. See the code here : https://github.com/Felix-73/CTRLX-SDK-APP-Sampler-Smart-check-sizing
base: core22
confinement: strict

# define how apps & services are exposed to host system
apps:
  app:
    command: datalayerClientSimple
    # interfaces to connect to https://snapcraft.io/docs/supported-interfaces
    plugs:
      - network
      - datalayer
    daemon: simple
    passthrough:
      restart-condition: always
      restart-delay: 10s

parts:
  datalayerclient:
    plugin: dump
    source: ./generated/build
    stage-packages:
      - libzmq5
      - ctrlx-datalayer

# describes which interface slots are supported by defining the plugs
plugs:
  datalayer:
    interface: content
    content: datalayer
    target: $SNAP_DATA/.datalayer
